# frozen_string_literal: true

require "git/cop/identity"
require "git/cop/kit/branch"
require "git/cop/kit/commit"
require "git/cop/styles/abstract"
require "git/cop/styles/commit_author_email"
require "git/cop/styles/commit_author_name_capitalization"
require "git/cop/styles/commit_author_name_parts"
require "git/cop/styles/commit_body_bullet"
require "git/cop/styles/commit_body_leading_space"
require "git/cop/styles/commit_body_line_length"
require "git/cop/styles/commit_body_phrase"
require "git/cop/styles/commit_body_present"
require "git/cop/styles/commit_subject_length"
require "git/cop/styles/commit_subject_prefix"
require "git/cop/styles/commit_subject_suffix"
require "git/cop/reporter"
require "git/cop/runner"
require "git/cop/cli"
